// src/xwayland/atoms.rs — X11 atom cache.

x11rb::atom_manager! {
    pub Atoms: AtomsCookie {
        // ICCCM
        WM_PROTOCOLS,
        WM_DELETE_WINDOW,
        WM_TAKE_FOCUS,
        WM_STATE,
        WM_CHANGE_STATE,
        WM_NAME,
        WM_CLASS,
        WM_TRANSIENT_FOR,
        WM_CLIENT_MACHINE,
        WM_HINTS,
        WM_NORMAL_HINTS,

        // EWMH
        _NET_SUPPORTED,
        _NET_SUPPORTING_WM_CHECK,
        _NET_ACTIVE_WINDOW,
        _NET_CLIENT_LIST,
        _NET_CLIENT_LIST_STACKING,
        _NET_WM_NAME,
        _NET_WM_VISIBLE_NAME,
        _NET_WM_STATE,
        _NET_WM_STATE_FULLSCREEN,
        _NET_WM_STATE_MAXIMIZED_VERT,
        _NET_WM_STATE_MAXIMIZED_HORZ,
        _NET_WM_STATE_HIDDEN,
        _NET_WM_STATE_FOCUSED,
        _NET_WM_STATE_MODAL,
        _NET_WM_STATE_ABOVE,
        _NET_WM_STATE_STICKY,
        _NET_WM_MOVERESIZE,
        _NET_WM_WINDOW_TYPE,
        _NET_WM_WINDOW_TYPE_NORMAL,
        _NET_WM_WINDOW_TYPE_DIALOG,
        _NET_WM_WINDOW_TYPE_TOOLBAR,
        _NET_WM_WINDOW_TYPE_MENU,
        _NET_WM_WINDOW_TYPE_UTILITY,
        _NET_WM_WINDOW_TYPE_SPLASH,
        _NET_WM_WINDOW_TYPE_DESKTOP,
        _NET_WM_WINDOW_TYPE_DROPDOWN_MENU,
        _NET_WM_WINDOW_TYPE_POPUP_MENU,
        _NET_WM_WINDOW_TYPE_TOOLTIP,
        _NET_WM_WINDOW_TYPE_NOTIFICATION,
        _NET_WM_WINDOW_TYPE_COMBO,
        _NET_WM_WINDOW_TYPE_DND,
        _NET_WM_PID,
        _NET_WM_DESKTOP,
        _NET_DESKTOP_VIEWPORT,
        _NET_DESKTOP_GEOMETRY,
        _NET_NUMBER_OF_DESKTOPS,
        _NET_CURRENT_DESKTOP,
        _NET_WORKAREA,
        _NET_CLOSE_WINDOW,
        _NET_FRAME_EXTENTS,

        // XDG
        _MOTIF_WM_HINTS,

        // XWayland
        WL_SURFACE_ID,
        WL_SURFACE_SERIAL,
        _XWAYLAND_MAY_GRAB_KEYBOARD,
        _XWAYLAND_RANDR_EMU_MONITOR_RECTS,

        // Misc
        UTF8_STRING,
        MANAGER,
        ATOM,
    }
}
